sudo: false

language: php

php:
    - 5.4
    - 5.5
    - 5.6

before_install:
    - composer self-update

install:
    - composer install --prefer-dist --no-progress --no-interaction

script:
    - composer test
